/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package br.com.sistemataxonomia.view;

import br.com.sistemataxonomia.modelo.Laboratorio;
import java.util.ArrayList;

/**
 *
 * @author samuel
 */
public class frmCadastLab extends javax.swing.JInternalFrame {

    ArrayList<Laboratorio> lstLaboratorio;
    
    public frmCadastLab() {
        lstLaboratorio = new ArrayList<Laboratorio>();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNomeLab = new javax.swing.JLabel();
        txfNome = new javax.swing.JTextField();
        lblEnderecoLab = new javax.swing.JLabel();
        txfEnderecoLab = new javax.swing.JTextField();
        lblCnpjLab = new javax.swing.JLabel();
        lblAreaDePesquisaLab = new javax.swing.JLabel();
        txfAreaDePesquisaLab = new javax.swing.JTextField();
        lblTelefoneLab = new javax.swing.JLabel();
        txfTelefoneLab = new javax.swing.JFormattedTextField();
        txfCnpjLab = new javax.swing.JFormattedTextField();
        btnSalvarLab = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Cadastro de Laboratório");
        setName("Cadastro de Laboratório"); // NOI18N
        getContentPane().setLayout(null);

        lblNomeLab.setText("Nome :");
        getContentPane().add(lblNomeLab);
        lblNomeLab.setBounds(30, 50, 50, 16);
        getContentPane().add(txfNome);
        txfNome.setBounds(80, 50, 240, 22);

        lblEnderecoLab.setText("Endereco :");
        getContentPane().add(lblEnderecoLab);
        lblEnderecoLab.setBounds(340, 50, 60, 16);
        getContentPane().add(txfEnderecoLab);
        txfEnderecoLab.setBounds(400, 50, 230, 22);

        lblCnpjLab.setText("Cnpj :");
        getContentPane().add(lblCnpjLab);
        lblCnpjLab.setBounds(30, 90, 40, 16);

        lblAreaDePesquisaLab.setText("Área de Pesquisa :");
        getContentPane().add(lblAreaDePesquisaLab);
        lblAreaDePesquisaLab.setBounds(340, 90, 100, 16);
        getContentPane().add(txfAreaDePesquisaLab);
        txfAreaDePesquisaLab.setBounds(440, 90, 190, 22);

        lblTelefoneLab.setText("Telefone :");
        getContentPane().add(lblTelefoneLab);
        lblTelefoneLab.setBounds(30, 130, 60, 16);
        getContentPane().add(txfTelefoneLab);
        txfTelefoneLab.setBounds(100, 130, 250, 22);

        try {
            txfCnpjLab.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###/####-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(txfCnpjLab);
        txfCnpjLab.setBounds(80, 90, 250, 22);

        btnSalvarLab.setText("Salvar");
        getContentPane().add(btnSalvarLab);
        btnSalvarLab.setBounds(210, 440, 72, 22);

        btnExcluir.setText("Excluir");
        getContentPane().add(btnExcluir);
        btnExcluir.setBounds(300, 440, 72, 22);

        setBounds(0, 0, 667, 508);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnSalvarLab;
    private javax.swing.JLabel lblAreaDePesquisaLab;
    private javax.swing.JLabel lblCnpjLab;
    private javax.swing.JLabel lblEnderecoLab;
    private javax.swing.JLabel lblNomeLab;
    private javax.swing.JLabel lblTelefoneLab;
    private javax.swing.JTextField txfAreaDePesquisaLab;
    private javax.swing.JFormattedTextField txfCnpjLab;
    private javax.swing.JTextField txfEnderecoLab;
    private javax.swing.JTextField txfNome;
    private javax.swing.JFormattedTextField txfTelefoneLab;
    // End of variables declaration//GEN-END:variables
}
