/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package br.com.sistemataxonomia.view;

import br.com.sistemataxonomia.modelo.Usuario;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author samuel
 */
public class frmCadastUsu extends javax.swing.JInternalFrame {
    
    ArrayList<Usuario> lstUsuario;
    
    boolean modoAlterarDeletar = false;
    
    String cod = "";
    
    int indiceLista = 0;
    
    public frmCadastUsu() {
        
        lstUsuario = new ArrayList<Usuario>();
        
        initComponents();
       

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtNomeUsu = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtCpf = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaUsuario = new javax.swing.JTable();
        btnSalvar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        txtArea = new javax.swing.JTextField();
        btnNovo = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Cadastro de Usuário");
        setToolTipText("");

        jLabel1.setText("Nome Usuário:");

        jLabel3.setText("CPF:");

        try {
            txtCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel4.setText("Área:");

        jScrollPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jScrollPane1MouseClicked(evt);
            }
        });

        tabelaUsuario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Cod.Usuario", "Nome", "CPF", "Área"
            }
        ));
        tabelaUsuario.setShowGrid(true);
        tabelaUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaUsuarioMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelaUsuario);

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnExcluir.setText("Deletar");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnNovo.setText("Novo");
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(txtNomeUsu, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(txtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(txtArea, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 760, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(260, 260, 260)
                .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(btnExcluir)
                .addGap(21, 21, 21)
                .addComponent(btnNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(txtNomeUsu, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(txtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(txtArea, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSalvar)
                    .addComponent(btnExcluir)
                    .addComponent(btnNovo)))
        );

        setBounds(0, 0, 794, 408);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
       
        
        
         String codUsuario = "";
        
         if (this.modoAlterarDeletar == true) {
            codUsuario = this.cod;

        } else {
            codUsuario = java.util.UUID.randomUUID().toString();
        }
         
         Usuario usuario = new Usuario(codUsuario,txtNomeUsu.getText(),
               txtCpf.getText(),txtArea.getText());
         
         this.modoNovo();
         
        
        if (this.modoAlterarDeletar == true) {
            
            lstUsuario.set(this.indiceLista, usuario);
            
            btnNovo.setEnabled(true);

        } else {
            lstUsuario.add(usuario);
        }        
        this.modoAlterarDeletar = false;
        
        this.carregarTabela();
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
      
        int input = JOptionPane.showConfirmDialog(null,
                "Deseja realmente excluir?", "Atenção!!!", JOptionPane.YES_NO_OPTION);

        if (input == 0) {

            lstUsuario.remove(this.indiceLista);

            this.carregarTabela();

        }
        
        this.modoNovo();
        
        btnNovo.setEnabled(true);
        
        
        
         
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void jScrollPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane1MouseClicked
        
    }//GEN-LAST:event_jScrollPane1MouseClicked

    private void tabelaUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaUsuarioMouseClicked
        this.modoAlterarDeletar = true;

        int row = this.tabelaUsuario.getSelectedRow();
        
        String codUsuario = (String) this.tabelaUsuario.getValueAt(row, 0);
       
        this.cod = codUsuario;

        int indice = 0;
        
        Usuario usuario = null;

        for (int i = 0; i < lstUsuario.size(); i++) {

            if (lstUsuario.get(i).getCodUsuario().equals(codUsuario)) {

                usuario = lstUsuario.get(i);
                indice = i;
                break;
            }
        }

        this.indiceLista = indice;

        txtNomeUsu.setText(usuario.getNome());
        txtCpf.setText(usuario.getCpf());
        txtArea.setText(usuario.getArea());
        
            this.habilitarCampos();
            
            btnSalvar.setEnabled(true);
            
            btnNovo.setEnabled(false);
            
            btnExcluir.setEnabled(true);
    }//GEN-LAST:event_tabelaUsuarioMouseClicked

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
         this.modoAlterarDeletar = false;
        
        this.modoNovo();
        
        this.carregarTabela();
        
        this.habilitarCampos();
        
        btnSalvar.setEnabled(true);
    }//GEN-LAST:event_btnNovoActionPerformed


    private void carregarTabela(){
        
        DefaultTableModel model = (DefaultTableModel) tabelaUsuario.getModel();

         
         model.setRowCount(0);
         
         for(Usuario usu : lstUsuario){
             
             model.addRow(new Object []{
                 usu.getCodUsuario(),
                 usu.getNome(),
                 usu.getCpf(),
                 usu.getArea()
             });
         }
         
         tabelaUsuario.setModel(model);
    }
    
    private void modoNovo(){
        
        txtNomeUsu.setText("");
        txtCpf.setText(""); 
        txtArea.setText("");
        
        txtNomeUsu.setEnabled(false);
        txtCpf.setEnabled(false);
        txtArea.setEnabled(false);
        
        btnSalvar.setEnabled(false);
        btnExcluir.setEnabled(false);
    }
    
    private void habilitarCampos() {
       
        txtNomeUsu.setEnabled(true);
        txtCpf.setEnabled(true);
        txtArea.setEnabled(true);
        
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelaUsuario;
    private javax.swing.JTextField txtArea;
    private javax.swing.JFormattedTextField txtCpf;
    private javax.swing.JTextField txtNomeUsu;
    // End of variables declaration//GEN-END:variables
}
