/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package br.com.sistemataxonomia.view;

import br.com.sistemataxonomia.modelo.Usuario;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author samuel
 */
public class frmCadastUsu extends javax.swing.JInternalFrame {
    
    ArrayList<Usuario> lstUsuario;
    
    boolean modoAlterarDeletar = false;
    
    String id = "";
    
    int indiceLista = 0;
    
    public frmCadastUsu() {
        lstUsuario = new ArrayList<Usuario>();
        initComponents();
       

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtNomeUsu = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtCpf = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaUsuario = new javax.swing.JTable();
        btnSalvar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        txtArea = new javax.swing.JTextField();
        btnNovo = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Cadastro de Usuário");
        setToolTipText("");
        getContentPane().setLayout(null);

        jLabel1.setText("Nome Usuário:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 40, 90, 16);
        getContentPane().add(txtNomeUsu);
        txtNomeUsu.setBounds(100, 40, 240, 30);

        jLabel3.setText("CPF:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(370, 40, 40, 16);

        try {
            txtCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(txtCpf);
        txtCpf.setBounds(420, 40, 190, 30);

        jLabel4.setText("Área:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(50, 80, 40, 16);

        jScrollPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jScrollPane1MouseClicked(evt);
            }
        });

        tabelaUsuario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Cod.Usuario", "Nome", "CPF", "Área"
            }
        ));
        tabelaUsuario.setShowGrid(true);
        tabelaUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaUsuarioMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelaUsuario);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 130, 760, 190);

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalvar);
        btnSalvar.setBounds(260, 340, 72, 22);

        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });
        getContentPane().add(btnExcluir);
        btnExcluir.setBounds(350, 340, 72, 22);
        getContentPane().add(txtArea);
        txtArea.setBounds(100, 80, 250, 30);

        btnNovo.setText("Novo");
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });
        getContentPane().add(btnNovo);
        btnNovo.setBounds(440, 340, 72, 22);

        setBounds(0, 0, 794, 408);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
       
        
        
         String idUsuario = "";
        
         if (this.modoAlterarDeletar == true) {
            idUsuario = this.id;

        } else {
            idUsuario = java.util.UUID.randomUUID().toString();
        }
         
         Usuario usuario = new Usuario(idUsuario,txtNomeUsu.getText(),
               txtCpf.getText(),txtArea.getText());
         
         this.LimparCampos();
        
        if (this.modoAlterarDeletar == true) {
            //ALTERO O VALOR NA POSIÇÃO DA LISTA
            lstUsuario.set(this.indiceLista, usuario);
            btnNovo.setEnabled(true);

        } else {
            lstUsuario.add(usuario);
        }        
        this.modoAlterarDeletar = false;
        
        this.CarregarTabela();
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
      
        int input = JOptionPane.showConfirmDialog(null,
                "Deseja realmente excluir?", "Atenção!!!", JOptionPane.YES_NO_OPTION);

        if (input == 0) {

            lstUsuario.remove(this.indiceLista);

            this.CarregarTabela();

        }
        
        this.LimparCampos();
        
        btnNovo.setEnabled(true);
        
        
         
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void jScrollPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jScrollPane1MouseClicked

    private void tabelaUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaUsuarioMouseClicked
        this.modoAlterarDeletar = true;

        //PEGA A LINHA SELECIONADA
        int row = this.tabelaUsuario.getSelectedRow();

        //RECUPERA O VALOr DA COLUNA ID ESTA NA 0
        String idUsuario = (String) this.tabelaUsuario.getValueAt(row, 0);

        //GUARDA O ID PARA ALTERAR/REMOVER
        this.id = idUsuario;

        int indice = 0;

        //RECUPERAR POR ID
        Usuario usuario = null;

        for (int i = 0; i < lstUsuario.size(); i++) {

            if (lstUsuario.get(i).getCodUsuario().equals(idUsuario)) {

                usuario = lstUsuario.get(i);
                indice = i;
                break;
            }
        }

        this.indiceLista = indice;

        txtNomeUsu.setText(usuario.getNome());
        txtCpf.setText(usuario.getCpf());
        txtArea.setText(usuario.getArea());
        
        this.habilitarCampos();
        
        btnSalvar.setEnabled(true);
            
        btnNovo.setEnabled(false);
            
        btnExcluir.setEnabled(true);
    }//GEN-LAST:event_tabelaUsuarioMouseClicked

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        this.modoAlterarDeletar = false;
        
        this.LimparCampos();
        
        this.CarregarTabela();
        
        this.habilitarCampos();
        
        btnSalvar.setEnabled(true);
    }//GEN-LAST:event_btnNovoActionPerformed


    private void CarregarTabela(){
        
        DefaultTableModel model = (DefaultTableModel) tabelaUsuario.getModel();

         
         model.setRowCount(0);
         
         for(Usuario usu : lstUsuario){
             
             model.addRow(new Object []{
                 usu.getCodUsuario(),
                 usu.getNome(),
                 usu.getCpf(),
                 usu.getArea()
             });
         }
         
         tabelaUsuario.setModel(model);
    }
    
    private void LimparCampos(){
        
        
        txtNomeUsu.setText("");
        txtCpf.setText("");
        txtArea.setText("");
        
        txtNomeUsu.setEnabled(false);
        txtCpf.setEnabled(false);
        txtArea.setEnabled(false);
        
        btnSalvar.setEnabled(false);
        btnExcluir.setEnabled(false);
    }
    
     private void habilitarCampos() {
        txtNomeUsu.setEnabled(true);
        txtCpf.setEnabled(true);
        txtArea.setEnabled(true);
     }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelaUsuario;
    private javax.swing.JTextField txtArea;
    private javax.swing.JFormattedTextField txtCpf;
    private javax.swing.JTextField txtNomeUsu;
    // End of variables declaration//GEN-END:variables
}
